### ISSUE TITLE
Error when tagInstagram has not been added to config

### ISSUE THREAD

**Issue by fadehelix** [tea3/hexo-tag-instagram#1]
I installed hexo-tag-instagram,
but didn't add the `tagInstagram` option to my hexo config
then I got following error in the console:
>TypeError: Cannot read property 'captioned' of undefined

**Comment by fadehelix** [comment]
I've created fix. Please check it: #2 
It checks for config and, if `tagInstagram` is not defined then sets the default value.

**Comment by tea3** [comment]
Thank you for your advice. Please update npm version .
