### ISSUE TITLE
imperfect display on small screen

### ISSUE THREAD

**Issue by Boycottangent** [tea3/hexo-tag-instagram#5]
**Even after adding the code from [this issue](https://github.com/tea3/hexo-tag-instagram/issues/3) the embedded ins still can't be displayed perfectly on small screen like iPhone SE.**

<img width="363" alt="xnip2019-01-23_17-21-54" src="https://user-images.githubusercontent.com/23280916/51596468-0427fa00-1f34-11e9-90e7-b9a8fb96abe8.png">

And you can see that embedded tweet doesn't have this problem.

It seems that a attribute related to "min-width" cause this problem

<img width="224" alt="image" src="https://user-images.githubusercontent.com/23280916/51596750-a47e1e80-1f34-11e9-86fa-1f4ae907d874.png">

after turning  this off on debug window, problem can be solved but I don't know how to fix it.

<img width="363" alt="image" src="https://user-images.githubusercontent.com/23280916/51596930-03439800-1f35-11e9-946b-3c3699b6d63e.png">

**Comment by tea3** [comment]
@Boycottangent 
Sorry, the best result seems to be different depending on the template. Thank you for the new reference information.

**Comment by kylebakerio** [comment]
This is an inherent problem with instagram embed code that I've also encountered before using this plugin elsewhere.

see this code for the gist of it and a reference to read more about the technique:

```
/* Responsive IFRAME Embed Encoding 
   Adapts fixed pixel IFRAME sizes and makes them responsive. 
   https://www.silvabokis.com/squarespace-tips/making-youtube-vimeo-and-instagram-iframes-responsive
   See Diaspora.responsify in local diaspora.js file for jquery code that dynamically adds these divs.
*/


/* First, define the common wrapper elements 
   Padding-top is for the fixed height header of the embedded content */

.youtubeWrapper, .vimeoWrapper, .instagramWrapper {
  position: relative;
  padding-top: 30px; height: 0; overflow: hidden;
}


/* Set the padding-bottom for 16:9 aspect ratio video from YouTube & Vimeo */ 
.youtubeWrapper, .vimeoWrapper {
  padding-bottom: 56.25%;      
}

/* Set padding-bottom for 5:6 aspect ratio Instagram content */
.instagramWrapper {
  padding-bottom: 120%;
}
    
/* For each content source, set the IFRAME to be top left and occupy 100% of width and height of the containing DIV wrapper */    
.youtubeWrapper iframe,
.youtubeWrapper object,
.youtubeWrapper embed,
.vimeoWrapper iframe,
.vimeoWrapper object,
.vimeoWrapper embed,
.instagramWrapper iframe,
.instagramWrapper object,
.instagramWrapper embed {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  /*min-width: 0px !important;*/
}

.no-min-width-iframe iframe { /* added by kyle, in ejs, not in the original jquery+css implementation; for some reason instagram embed for 2015 and earlier didn't work, while 2016 and newer did. adding this fixed it. */
  min-width: 0px !important;
}```

Might be neat if this plugin integrated this, though.

**Comment by tea3** [comment]
@kylebakerio Thank your for suggestion. I tried the code on my site but it didn't work.

In the case of [my site](https://photo-tea.com/p/hexo-tag-instagram/), I'm forcibly setting width from jQeury.  This makes it possible to scroll on smaller screens. 

``` javascript
$(".twitter-container, .instagram-wrapper").each(function(i){
    var twitterEmdWidth = Math.floor($(this).width());
    $(this).css({
      "width": Math.floor( twitterEmdWidth ) + "px" ,
      "overflow": "auto"
    });
});
```

**Comment by kylebakerio** [comment]
This wasn't all code needed to implement--follow the links mentioned in the css code example to understand the technique better.

**Comment by Boycottangent** [comment]
Find out the solution, It seems that [instagram's embed js](http://platform.instagram.com/en_US/embeds.js) injects the "min-width" restriction and this js file is used by index.js in line 44
``` javascript
..<script async="" defer="" src="//platform.instagram.com/en_US/embeds.js"></script>..
```
Modify this js by remove the `\n  min-width: 326px;` in it, save it in js folder and use it locally.
``` javascript
..<script async="" defer="" src="/js/your file name.js"></script>..
```

This will solve the problem.

**Comment by tea3** [comment]
@Boycottangent Thank you for all the details. Including the modified embeds.js in the plug-in is probably the solution.
